#!/usr/bin/env Rscript
# 
#################################################################
# cramtofastq_from_iRODs_based_cram_manifest.R
# This script takes an iRODs manifest and generates an sh file with a series of command job submission to import, sort and transform to fastq, CRAMs from iRODs
# 
#  The Project folder should have the following  structure before running this program:
#  /My_project_folder/
#     metadata/manifests/My_cram_manifest_INFO_from_iRODS.txt
# 
# The program will create the  following directories:
# /My_project_folder/
#     /fastqs
#     /logs
#       /cramtofastqs
#  
# 
#Author: Martin Del Castillo Velasco-Herrera - mdc1@sanger.ac.uk
###################################################################
progname<-"cramtofastq_from_iRODs_based_cram_manifest.R"
#Loading Libraries
suppressMessages(library(optparse))
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))

#Get the options for the script
####### Set the options list of the program
option_list<- list(
  make_option(c("--manifest"), action="store_true", default=NA, type="character", help="This is the project iRODs manifest file name generated by sequencescape project ID number using Build_manifest_from_irods_cram_information.R
                IT should be locatet in the folder /projectdir/metadata/ for this command to work"), 
  make_option(c("--projectdir"), action="store_true", type="character", default=NA, help="This is the location where the main project folder is (if provided, else it will assume the current directory)"),
  make_option(c("--studyID"), action="store_true", type="character", default=NA, help="This is the sequencescape study_ID"),
  make_option(c("--mem"), action="store_true", type="character", default="6000", help="This is the RAM memory amount (in Mb) set for the conversion jobs")
)
#### Indicate that the file follows to the options used
parser<- OptionParser(usage = paste(progname, " [options] --manifest My_cram_manifest_INFO_from_iRODS.txt, --studyID 6510 --projectdir  /My_project_folder/ ",sep=""), option_list=option_list)
arguments<- parse_args(parser, positional_arguments = 0) # no files after the options shoudl be provided
#FOR testing purposes
# arguments<- parse_args(parser,
#                        args=c("--manifest","6633_cram_manifest_INFO_from_iRODS.txt","--projectdir","/lustre/scratch119/casm/team113da/projects/6633_PDX_models_Latin_America_WES"), #For tests
#                         positional_arguments = 0) # no files after the options should be provided

# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults,
opt<-arguments$options


#Verify that the outidr was set
if(is.na(opt$projectdir)){
  projectdir<-paste(getwd(),"/",sep="")
} else {
  projectdir<-opt$projectdir
}
#Verify there is a study ID provided
if(is.na(opt$studyID)){
  stop(paste0("NO STUDY ID provides, Check file or see the help for requirements"))
}



#Verify that the input manifest exitst was set 
manifdir<-file.path(projectdir, "metadata", "manifests")
manif_name<-file.path(manifdir,opt$manifest)
if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}
#Getting the study id
studyid_manif<-strsplit(opt$manifest,split = "_", fixed=T)[[1]][1]
studyid<- opt$studyID
if(studyid_manif!=studyid){
  stop(paste("The Study ID of manifest file:", manif_name, ". \n Is not the same as the one provided for studyID: ", studyid, sep=""))
}

#Write some output starting message
write(paste("#########################################\n", progname, date(),"The study ID found from manifest name is: ",studyid, "\nThe Manifest provided:", opt$manifest,"\n",
            "The projectdir provided is:", projectdir, "\n", 
            "The study is:", opt$studyID, "\n", 
            "The project manifest found is: ",manif_name, "\n",sep=" "), stdout())

#######################################################################
#Defining the directories for the analyses and GENERAL VARIABLES

#Set of folders for the outputs
fqfolder<-file.path(projectdir, "fastqs")
logfolder<-paste(projectdir, "/logs", sep="")
fqlogfolder<-paste(projectdir, "/logs/cramtofastqs",sep="")


#Make the folders
dir.create(fqfolder)
dir.create(fqlogfolder, recursive = TRUE)

#PAHTS to the programs required
samtoolsmod_version<-"module load samtools-1.14/python-3.12.0 ;"
samtools<-"samtools"

######################
#EXMAPLEs of job to transform cram from iRODs to fastq
# bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz -n '

#############################################################################################
# 1. Read the file  manifest file  ------------------
manif<-read.csv(manif_name, header=TRUE, stringsAsFactors=FALSE, sep="\t")
#To take as a test I will generate things first for the biggest sample
#test_sampl<-manif[manif$total_reads==228701454,]

#############################################################################################
# 2. Create the sh file that will submit  the jobs for the iRODS cram to fastq transformation  ------------------
i<-0
fq1<-NULL
fq2<-NULL
smp_runid<-NULL
cmds<-NULL
for (i in 1:dim(manif)[1]){
  fastq1<-NULL
  fastq2<-NULL
  sdoutf<-NULL
  serrf<-NULL
  tsrunid<-NULL
  temp<-manif[i,]
  tsrunid<- paste0(temp$sample,"_",temp$id_run,"_",temp$lane,"#",temp$tag_index)
  cmd<-NULL
  # give name to errorfiles
  sdoutf<-file.path(fqlogfolder, paste("cramtofq_",i,".o", sep = ""))
  serrf<-file.path(fqlogfolder, paste("cramtofq_",i,".e", sep = ""))
  #For the fastqs
  fastq1<-file.path(fqfolder, paste(tsrunid, "_R1.fastq.gz", sep=""))
  fastq2<-file.path(fqfolder, paste(tsrunid, "_R2.fastq.gz", sep=""))
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz '
  cmd<-as.character(paste("bsub -q normal -M ", opt$mem, " -R",shQuote(paste0("select[mem>",opt$mem,"] rusage[mem=", opt$mem,"] span[hosts=1]")) , " -n 6 -o ", sdoutf," -e ",serrf, 
             " '",samtoolsmod_version," iget ", temp$cram_irods_location, " - | ", samtools,
             " collate -u --threads 6 -O - | ",
             samtools, " fastq --threads 6 -N -1 ",fastq1, " -2 ", fastq2, "'",
             sep=""))  
  #ADD the jobs
  cmds<-c(cmds,cmd)
  fq1<-c(fq1,fastq1)
  fq2<-c(fq2,fastq2)
  smp_runid<-c(smp_runid, tsrunid)
}
#add the fastq info to the manifest
manif$fastq1<-fq1
manif$fastq2<-fq2
manif$sample_fqrunid<-smp_runid
#Create the sh file 
write.table(c("#!/bin/sh", cmds), file=file.path(projectdir,"scripts", paste0(studyid,"_cramtofastq_from_iRODs_jobs.sh")), quote = F, col.names = F, row.names = F, sep = "\n")


#############################################################################################
# 3. Create the per sample manifest   ------------------

#############################################################################################
# 4. Plot the number of reads sequence d   ------------------
manif$donor_id<- substr(manif$sample_donor_id, start = 1,stop = 6)
cols<-colorRampPalette(rev(brewer.pal(n=12,name = "Paired" )))(length(unique(manif$donor_id)))
nreads<-ggplot(data = manif, aes(x=sample_supplier_name, y=total_reads))+
  geom_bar(aes(fill=donor_id), stat = "identity")+
  scale_fill_manual(values = cols)+
  theme(legend.title = element_text(colour = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("Number of reads sequenced by sample")+
  xlab("Supplier Sample Name")+
  ylab("Total num. of reads sequenced")

pdf(file = file.path( fqfolder, "QC_plot_totNumReads_seq_per_sample_byDonorID.pdf") )
nreads
dev.off()

#############################################################################################
# 5. Save new full manifest   ------------------
#Create new manifest name
tnw_manif<-as.vector(strsplit(manif_name, split = "/")[[1]])
tnw_manif<-gsub(".txt", "_wbam_counts_qc.txt", tnw_manif[length(tnw_manif)])
write.table(manif,file=file.path(manifdir, tnw_manif), quote = F, col.names = T, row.names = F, sep = "\t") 
